// simpleSheet5e/simpleSheet5e/src/app/components/app-header/app-header.component.ts
import { Component, Input } from '@angular/core';
import { Service } from '../../service';

@Component({
  selector: 'app-header',
  imports: [],
  templateUrl: './app-header.component.html',
  styleUrl: './app-header.component.scss'
})
export class AppHeaderComponent {
  @Input() isUpdated: boolean | null = false;
  constructor(private service: Service) {}
}


<header>
    <h1>Simple Sheet 5e</h1>
    <div class="header-buttons">
        <div class="input-wrapper">
            <button id="save-button" disabled="!data.state.isUpdated" click="service.saveToStorage()">Save</button>
        </div>
    </div>
</header>

// simpleSheet5e/simple-sheet-5e/src/components/AppHeader.vue
<script setup lang="ts">
import { Store } from '../store';
import { Service } from '../service';
import { toRaw } from 'vue';
// goes on the Button, eventually --  :disabled="!service.StoreRef.value.state.isUpdated"

const service = new Service();
const data = toRaw({...Store});
</script>

<template>
    <header>
        <h1>Simple Sheet 5e</h1>
        <div class="header-buttons">
            <div class="input-wrapper">
                <button id="save-button" :disabled="!data.state.isUpdated" @click="service.saveToStorage()">Save</button>
            </div>
        </div>
    </header>
</template>

<style scoped>
    header {
        flex: 0 0 50px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
</style>
